export interface Datos {
    date: number;
    fechai: string;
    fft01: string;
    fft02: string;
    fft03: string;
    fft05: string;
    fft06: string;
    fft09: string;
    fft10: string;
    fft11: string;
    fft12: string;
    fft13: string;
    ffc07: string;
    fft08ie1: string;
    fft08ie2: string;
    fft08pe1: string;
    fft08pe2: string;
    fft151: string;
    fft152: string;
    fft071: string;
    fft072: string;
    dia: string;
    mes: string;
//    mesl: string;
    anio: string;
    s1: string;
    s2: string;
//    s3: string;
    fechaf: string;
    razon: string;
    giro: string;
    nocontrol: string;
    nombre: string;
    nomcom: string;
    id: string;
    folio: string;
    id2: string;
    folio2: string;
    foliorp: string;
    cedula: string;
    tel: string;
    correo: string;
    fax: string;
    rfc: string;
    calle: string;
    colonia: string;
    munic: string;
    estado: string;
    cp: string;
    logo: string;
    planos: string;
    tipos: string;
    tension: string;
    cargai: number;
    alcance: number;
    factor: number;
    cargadem: number;
    corriente: number;
    volts: string;
    sub: string;
    csub: string;
    area: string;
    costo: number;
    costol: string;
    cent: number;
    instal: string;
//    nom1: boolean;
//    nom7: boolean;
//    nom13: boolean;
 //   revp: boolean;
//    verfs: boolean;
//    verfbt: boolean;
    ambien: string;
    memo: string;
    nombreuv: string;
    nombrers: string;
    nombrerp: string;
    cargouv: string;
    pedido: number;
    fpago: string;
    vigencia: string;
    intro: string;
    intro2: string;
    dato1: string;
    dato2: string;
    dato3: string;
    dato4: string;
    dato5: string;
    dato6: string;
    dato7: string;
    dato8: string;
    dato9: string;
    dato10: string;
    dato11: string;
    dato12: string;
}
