export interface Datos {
    date: number;
    fechai: string;
    fft02: string;
    fft03: string;
    fft05: string;
    fft06: string;
    fft09: string;
    fft10: string;
    fft11: string;
    ffc07: string;
    dia: string;
    mes: string;
//    mesl: string;
    anio: string;
///    s1: string;
//    s2: string;
//    s3: string;
    fechaf: string;
    razon: string;
    giro: string;
    nocontrol: string;
    nombre: string;
  //  id: string;
  //  folio: string;
    tel: string;
    correo: string;
    fax: string;
    rfc: string;
    calle: string;
    colonia: string;
    munic: string;
    estado: string;
    cp: number;
    logo: string;
    planos: string;
    tipos: string;
    tension: string;
    cargai: number;
    alcance: number;
    factor: number;
    cargadem: number;
    corriente: number;
    volts: string;
    sub: number;
    area: number;
    costo: number;
    costol: string;
    instal: string;
//    nom1: boolean;
//    nom7: boolean;
//    nom13: boolean;
 //   revp: boolean;
//    verfs: boolean;
//    verfbt: boolean;
    ambien: string;
    memo: string;
    nombreuv: string;
    cargouv: string;
    pedido: number;
    fpago: string;
    vigencia: string;
    intro: string;
}
